#!/usr/bin/env bash

# check docker image for building
if [ "$(docker images -q 5game-bld 2> /dev/null)" == "" ]; then
  echo "Build Docker image as 5game-bld"
  docker image build --compress -t 5game-bld -f ./Dockerfile.bld .
fi

# create install dir
mkdir -p appins 

# execute commands 
if [ $# -ne 0 ]; then
  echo "$@ ..."
  docker run -v `pwd`:`pwd` -w `pwd` -i -t \
  --rm --network host \
  5game-bld $@
else
  echo "Start building ..."
  docker run -v `pwd`:`pwd` -w `pwd` -i -t \
  --rm --network host \
  5game-bld bash
fi
